# Generated by Django 4.1.1 on 2023-02-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coe',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
