version: "3"

services:
  nginx:
    build: ./Nginx
    container_name: qpgen-nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - django
      - nextjs
      - db


  django:
    build: ./Backend
    container_name: qpgen-django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    volumes:
      - ./Backend/:/app
      - static:/app/static
      - media:/app/media
    depends_on:
      - db

  nextjs:
    build: ./Frontend
    container_name: qpgen-nextjs
    command: yarn dev
    ports:
      - 3001:3000
    env_file:
      - ./.env.dev
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./Frontend/:/app
      - /app/node_modules
    depends_on:
      - django

  db:
    image: postgres:12-alpine
    container_name: qpgen-db
    ports:
      - 5433:5432
    env_file: ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: qpgen
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin


volumes:
  postgres_data:
  media:
  static:
