# Generated by Django 4.2.4 on 2023-10-01 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0038_exammark_is_end_sem_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndSemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='endsem')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EndSemSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.PositiveIntegerField()),
                ('marks', models.JSONField(default=list)),
                ('counts', models.JSONField(default=list)),
                ('choices', models.JSONField(default=list)),
                ('faculties', models.ManyToManyField(blank=True, related_name='endsem_faculties', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endsem_faculties', to='questions.subject')),
            ],
            options={
                'verbose_name': 'End Sem Subject',
                'verbose_name_plural': 'End Sem Subjects',
                'unique_together': {('semester', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='EndSemQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('roman', models.PositiveIntegerField(blank=True, null=True)),
                ('option', models.PositiveIntegerField(blank=True, null=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('mark', models.PositiveIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endsem_questions', to='endsem.endsemsubject')),
            ],
            options={
                'ordering': ['subject', 'part', 'number', 'roman', 'option'],
            },
        ),
    ]
