# Generated by Django 4.2.4 on 2023-10-16 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0038_exammark_is_end_sem_format'),
        ('endsem', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='endsemsubject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='endsemsubject',
            name='regulation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='endsem_regulations', to='questions.regulation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endsemsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endsem_subjects', to='questions.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='endsemsubject',
            unique_together={('regulation', 'semester', 'subject')},
        ),
    ]
