# Generated by Django 4.2.4 on 2023-10-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endsem', '0002_alter_endsemsubject_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endsemsubject',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='endsemsubject',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
