# Generated by Django 4.2.4 on 2024-04-03 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0039_alter_markrange_end_alter_markrange_start_and_more'),
        ('endsem', '0003_endsemsubject_is_external_endsemsubject_is_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='endsemquestion',
            name='btl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='questions.bloomstaxonomylevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endsemquestion',
            name='co',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
