# Generated by Django 4.1.1 on 2022-11-25 07:41

from django.db import migrations
import django_choices_field.fields
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousyearsqp',
            name='month',
            field=django_choices_field.fields.TextChoicesField(choices=[('A/M', 'A/M'), ('N/D', 'N/D')], choices_enum=questions.models.PreviousYearsQP.MonthEnum, max_length=3),
        ),
    ]
