# Generated by Django 4.1.1 on 2022-09-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloomstaxonomylevel',
            name='name',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('name', 'subject')},
        ),
    ]
