# Generated by Django 4.1.1 on 2022-09-15 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_subject_co_description_subject_course_outcome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quesion',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AlterField(
            model_name='question',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.markrange'),
        ),
    ]
