# Generated by Django 4.1.1 on 2022-09-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_rename_quesion_question_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_mark',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='start_mark',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
