# Generated by Django 4.1.1 on 2022-09-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_end_mark_question_start_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_mark',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='start_mark',
            field=models.IntegerField(blank=True),
        ),
    ]
