# Generated by Django 4.1.1 on 2022-09-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_question_previous_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='previous_years',
            field=models.ManyToManyField(blank=True, related_name='questions', to='questions.previousyearsqp'),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
