# Generated by Django 4.1.1 on 2022-10-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_question_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facultieshandling',
            unique_together={('course', 'subject')},
        ),
    ]
