# Generated by Django 4.1.1 on 2022-10-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_alter_facultieshandling_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='branch_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
