# Generated by Django 4.1.1 on 2023-02-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_alter_question_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='co_description',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='coe',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='course_outcome',
        ),
        migrations.AddField(
            model_name='lesson',
            name='objective',
            field=models.TextField(default='Course Objective'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='outcome',
            field=models.TextField(default='Course Outcome'),
            preserve_default=False,
        ),
    ]
