# Generated by Django 4.1.1 on 2023-02-15 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_remove_subject_co_description_remove_subject_coe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='outcome_btl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='questions.bloomstaxonomylevel'),
            preserve_default=False,
        ),
    ]
