# Generated by Django 4.1.1 on 2023-02-21 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_lesson_outcome_btl'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='priority',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
