# Generated by Django 4.1.1 on 2023-02-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_createsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createsubject',
            name='secret',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
