# Generated by Django 4.1.1 on 2023-02-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_alter_createsubject_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createsubject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_subjects', to='questions.subject'),
        ),
    ]
