# Generated by Django 4.1.1 on 2023-02-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_alter_createsubject_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='outcome_btl',
        ),
        migrations.AddField(
            model_name='lesson',
            name='outcome_btl',
            field=models.ManyToManyField(related_name='lessons', to='questions.bloomstaxonomylevel'),
        ),
    ]
