# Generated by Django 4.1.1 on 2023-02-25 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0020_remove_lesson_outcome_btl_lesson_outcome_btl'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_subjects', to=settings.AUTH_USER_MODEL)),
                ('syllabus', models.ManyToManyField(blank=True, null=True, related_name='created_syllabus', to='questions.syllabus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CreateSubject',
        ),
    ]
