# Generated by Django 4.1.1 on 2023-02-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_createsyllabus_delete_createsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createsyllabus',
            name='syllabus',
            field=models.ManyToManyField(related_name='created_syllabus', to='questions.syllabus'),
        ),
    ]
