# Generated by Django 4.1.1 on 2023-02-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_alter_createsyllabus_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createsyllabus',
            name='syllabus',
            field=models.ManyToManyField(blank=True, related_name='created_syllabus', to='questions.syllabus'),
        ),
    ]
