# Generated by Django 4.1.1 on 2023-02-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_alter_createsyllabus_syllabus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='syllabus',
            unique_together={('course', 'lesson')},
        ),
    ]
