# Generated by Django 4.1.1 on 2023-02-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_alter_syllabus_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='scenario_based',
            field=models.BooleanField(default=False),
        ),
    ]
