# Generated by Django 4.1.1 on 2023-03-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_question_scenario_based'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='priority',
        ),
    ]
