# Generated by Django 4.1.1 on 2023-04-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_remove_topic_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestionsJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
