# Generated by Django 4.1.1 on 2023-07-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_generatedquestionsjson'),
        ('questions', '0029_alter_image_photo'),
    ]

    operations = [
    ]
