# Generated by Django 4.1.1 on 2023-07-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_merge_20230725_1202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedQuestionsJSON',
        ),
    ]
