# Generated by Django 4.1.1 on 2023-07-29 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0031_delete_generatedquestionsjson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markrange',
            name='end',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='markrange',
            name='start',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
