# Generated by Django 4.2.4 on 2023-08-24 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0034_alter_bloomstaxonomylevel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(help_text='Displayed in Question Paper', max_length=200, unique=True)),
                ('total', models.IntegerField()),
                ('marks', models.JSONField()),
                ('counts', models.JSONField()),
                ('choices', models.JSONField()),
                ('units', models.JSONField()),
                ('time', models.CharField(max_length=25)),
                ('order', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(related_name='analysis', to='questions.course')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='questions.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='questions.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisBTL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_btl', to='questions.analysis')),
                ('btl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_btl', to='questions.bloomstaxonomylevel')),
            ],
            options={
                'unique_together': {('analysis', 'btl')},
            },
        ),
    ]
