# Generated by Django 4.2.4 on 2023-08-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0036_alter_exam_options_remove_exam_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisbtl',
            options={'ordering': ['btl']},
        ),
    ]
