# Generated by Django 4.2.4 on 2023-09-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0037_alter_analysisbtl_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammark',
            name='is_end_sem_format',
            field=models.BooleanField(default=False),
        ),
    ]
