# Generated by Django 4.2.4 on 2024-01-22 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0038_exammark_is_end_sem_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markrange',
            name='end',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='markrange',
            name='start',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='previousyearsqp',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='year',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
