# Generated by Django 4.1.1 on 2023-02-19 11:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, validators=[users.models.validate_email])),
                ('password', models.CharField(max_length=150)),
                ('email_verfied', models.BooleanField(default=False)),
                ('email_secret', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
