# Generated by Django 4.1.1 on 2023-02-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_newusers_newuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='email_verfied',
            new_name='email_verified',
        ),
    ]
