# Generated by Django 4.1.1 on 2023-02-19 12:25

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_newuser_email_alter_newuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=150, unique=True, validators=[users.models.validate_email]),
        ),
    ]
