# Generated by Django 4.1.1 on 2023-02-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_newuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email_secret',
            field=models.CharField(blank=True, default='', editable=False, max_length=120),
        ),
    ]
