# Generated by Django 4.1.1 on 2023-02-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_newuser_email_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
